/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ManagerRouteImport } from './routes/manager'
import { Route as SuperAdminRouteImport } from './routes/super-admin'
import { Route as AuthIndexRouteImport } from './routes/auth.index'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as ManagerIndexRouteImport } from './routes/manager.index'
import { Route as ManagerDashboardRouteImport } from './routes/manager.dashboard'
import { Route as ManagerSalesRouteImport } from './routes/manager.sales'
import { Route as SuperAdminIndexRouteImport } from './routes/super-admin.index'
import { Route as SuperAdminDashboardRouteImport } from './routes/super-admin.dashboard'
import { Route as ManagerAssessmentsIndexRouteImport } from './routes/manager.assessments.index'
import { Route as ManagerAssessmentsAssessmentIdRouteImport } from './routes/manager.assessments.$assessmentId'
import { Route as ManagerAssessmentsNewRouteImport } from './routes/manager.assessments.new'
import { Route as ManagerExpenseIndexRouteImport } from './routes/manager.expense.index'
import { Route as ManagerFollowUpIndexRouteImport } from './routes/manager.follow-up.index'
import { Route as ManagerFollowUpFollowUpIdRouteImport } from './routes/manager.follow-up.$followUpId'
import { Route as ManagerMaterialsIndexRouteImport } from './routes/manager.materials.index'
import { Route as ManagerMaterialsMaterialIdRouteImport } from './routes/manager.materials.$materialId'
import { Route as ManagerMaterialsNewRouteImport } from './routes/manager.materials.new'
import { Route as ManagerOutdoorIndexRouteImport } from './routes/manager.outdoor.index'
import { Route as ManagerOutdoorVisitIdRouteImport } from './routes/manager.outdoor.$visitId'
import { Route as ManagerOutdoorNewRouteImport } from './routes/manager.outdoor.new'
import { Route as ManagerPackagesIndexRouteImport } from './routes/manager.packages.index'
import { Route as ManagerPatientsIndexRouteImport } from './routes/manager.patients.index'
import { Route as ManagerPatientsPatientIdRouteImport } from './routes/manager.patients.$patientId'
import { Route as ManagerPaymentsIndexRouteImport } from './routes/manager.payments.index'
import { Route as ManagerPaymentsPaymentIdRouteImport } from './routes/manager.payments.$paymentId'
import { Route as ManagerPaymentsCollectRouteImport } from './routes/manager.payments.collect'
import { Route as ManagerPaymentsPackagesRouteImport } from './routes/manager.payments.packages'
import { Route as ManagerTherapyIndexRouteImport } from './routes/manager.therapy.index'
import { Route as ManagerTherapySessionIdRouteImport } from './routes/manager.therapy.$sessionId'
import { Route as ManagerTherapyNewRouteImport } from './routes/manager.therapy.new'
import { Route as SuperAdminBranchesIndexRouteImport } from './routes/super-admin.branches.index'
import { Route as SuperAdminBranchesBranchIdRouteImport } from './routes/super-admin.branches.$branchId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerRoute = ManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const ManagerIndexRoute = ManagerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerDashboardRoute = ManagerDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerSalesRoute = ManagerSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => ManagerRoute,
} as any)
const SuperAdminIndexRoute = SuperAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminDashboardRoute = SuperAdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => SuperAdminRoute,
} as any)
const ManagerAssessmentsIndexRoute = ManagerAssessmentsIndexRouteImport.update({
  id: '/assessments/',
  path: '/assessments/',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerAssessmentsAssessmentIdRoute =
  ManagerAssessmentsAssessmentIdRouteImport.update({
    id: '/assessments/$assessmentId',
    path: '/assessments/$assessmentId',
    getParentRoute: () => ManagerRoute,
  } as any)
const ManagerAssessmentsNewRoute = ManagerAssessmentsNewRouteImport.update({
  id: '/assessments/new',
  path: '/assessments/new',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerExpenseIndexRoute = ManagerExpenseIndexRouteImport.update({
  id: '/expense/',
  path: '/expense/',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerFollowUpIndexRoute = ManagerFollowUpIndexRouteImport.update({
  id: '/follow-up/',
  path: '/follow-up/',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerFollowUpFollowUpIdRoute =
  ManagerFollowUpFollowUpIdRouteImport.update({
    id: '/follow-up/$followUpId',
    path: '/follow-up/$followUpId',
    getParentRoute: () => ManagerRoute,
  } as any)
const ManagerMaterialsIndexRoute = ManagerMaterialsIndexRouteImport.update({
  id: '/materials/',
  path: '/materials/',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerMaterialsMaterialIdRoute =
  ManagerMaterialsMaterialIdRouteImport.update({
    id: '/materials/$materialId',
    path: '/materials/$materialId',
    getParentRoute: () => ManagerRoute,
  } as any)
const ManagerMaterialsNewRoute = ManagerMaterialsNewRouteImport.update({
  id: '/materials/new',
  path: '/materials/new',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerOutdoorIndexRoute = ManagerOutdoorIndexRouteImport.update({
  id: '/outdoor/',
  path: '/outdoor/',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerOutdoorVisitIdRoute = ManagerOutdoorVisitIdRouteImport.update({
  id: '/outdoor/$visitId',
  path: '/outdoor/$visitId',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerOutdoorNewRoute = ManagerOutdoorNewRouteImport.update({
  id: '/outdoor/new',
  path: '/outdoor/new',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerPackagesIndexRoute = ManagerPackagesIndexRouteImport.update({
  id: '/packages/',
  path: '/packages/',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerPatientsIndexRoute = ManagerPatientsIndexRouteImport.update({
  id: '/patients/',
  path: '/patients/',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerPatientsPatientIdRoute =
  ManagerPatientsPatientIdRouteImport.update({
    id: '/patients/$patientId',
    path: '/patients/$patientId',
    getParentRoute: () => ManagerRoute,
  } as any)
const ManagerPaymentsIndexRoute = ManagerPaymentsIndexRouteImport.update({
  id: '/payments/',
  path: '/payments/',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerPaymentsPaymentIdRoute =
  ManagerPaymentsPaymentIdRouteImport.update({
    id: '/payments/$paymentId',
    path: '/payments/$paymentId',
    getParentRoute: () => ManagerRoute,
  } as any)
const ManagerPaymentsCollectRoute = ManagerPaymentsCollectRouteImport.update({
  id: '/payments/collect',
  path: '/payments/collect',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerPaymentsPackagesRoute = ManagerPaymentsPackagesRouteImport.update({
  id: '/payments/packages',
  path: '/payments/packages',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerTherapyIndexRoute = ManagerTherapyIndexRouteImport.update({
  id: '/therapy/',
  path: '/therapy/',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerTherapySessionIdRoute = ManagerTherapySessionIdRouteImport.update({
  id: '/therapy/$sessionId',
  path: '/therapy/$sessionId',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerTherapyNewRoute = ManagerTherapyNewRouteImport.update({
  id: '/therapy/new',
  path: '/therapy/new',
  getParentRoute: () => ManagerRoute,
} as any)
const SuperAdminBranchesIndexRoute = SuperAdminBranchesIndexRouteImport.update({
  id: '/branches/',
  path: '/branches/',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminBranchesBranchIdRoute =
  SuperAdminBranchesBranchIdRouteImport.update({
    id: '/branches/$branchId',
    path: '/branches/$branchId',
    getParentRoute: () => SuperAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/manager': typeof ManagerRouteWithChildren
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/manager/dashboard': typeof ManagerDashboardRoute
  '/manager/sales': typeof ManagerSalesRoute
  '/super-admin/dashboard': typeof SuperAdminDashboardRoute
  '/auth/': typeof AuthIndexRoute
  '/manager/': typeof ManagerIndexRoute
  '/super-admin/': typeof SuperAdminIndexRoute
  '/manager/assessments/$assessmentId': typeof ManagerAssessmentsAssessmentIdRoute
  '/manager/assessments/new': typeof ManagerAssessmentsNewRoute
  '/manager/follow-up/$followUpId': typeof ManagerFollowUpFollowUpIdRoute
  '/manager/materials/$materialId': typeof ManagerMaterialsMaterialIdRoute
  '/manager/materials/new': typeof ManagerMaterialsNewRoute
  '/manager/outdoor/$visitId': typeof ManagerOutdoorVisitIdRoute
  '/manager/outdoor/new': typeof ManagerOutdoorNewRoute
  '/manager/patients/$patientId': typeof ManagerPatientsPatientIdRoute
  '/manager/payments/$paymentId': typeof ManagerPaymentsPaymentIdRoute
  '/manager/payments/collect': typeof ManagerPaymentsCollectRoute
  '/manager/payments/packages': typeof ManagerPaymentsPackagesRoute
  '/manager/therapy/$sessionId': typeof ManagerTherapySessionIdRoute
  '/manager/therapy/new': typeof ManagerTherapyNewRoute
  '/super-admin/branches/$branchId': typeof SuperAdminBranchesBranchIdRoute
  '/manager/assessments/': typeof ManagerAssessmentsIndexRoute
  '/manager/expense/': typeof ManagerExpenseIndexRoute
  '/manager/follow-up/': typeof ManagerFollowUpIndexRoute
  '/manager/materials/': typeof ManagerMaterialsIndexRoute
  '/manager/outdoor/': typeof ManagerOutdoorIndexRoute
  '/manager/packages/': typeof ManagerPackagesIndexRoute
  '/manager/patients/': typeof ManagerPatientsIndexRoute
  '/manager/payments/': typeof ManagerPaymentsIndexRoute
  '/manager/therapy/': typeof ManagerTherapyIndexRoute
  '/super-admin/branches/': typeof SuperAdminBranchesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/manager/dashboard': typeof ManagerDashboardRoute
  '/manager/sales': typeof ManagerSalesRoute
  '/super-admin/dashboard': typeof SuperAdminDashboardRoute
  '/auth': typeof AuthIndexRoute
  '/manager': typeof ManagerIndexRoute
  '/super-admin': typeof SuperAdminIndexRoute
  '/manager/assessments/$assessmentId': typeof ManagerAssessmentsAssessmentIdRoute
  '/manager/assessments/new': typeof ManagerAssessmentsNewRoute
  '/manager/follow-up/$followUpId': typeof ManagerFollowUpFollowUpIdRoute
  '/manager/materials/$materialId': typeof ManagerMaterialsMaterialIdRoute
  '/manager/materials/new': typeof ManagerMaterialsNewRoute
  '/manager/outdoor/$visitId': typeof ManagerOutdoorVisitIdRoute
  '/manager/outdoor/new': typeof ManagerOutdoorNewRoute
  '/manager/patients/$patientId': typeof ManagerPatientsPatientIdRoute
  '/manager/payments/$paymentId': typeof ManagerPaymentsPaymentIdRoute
  '/manager/payments/collect': typeof ManagerPaymentsCollectRoute
  '/manager/payments/packages': typeof ManagerPaymentsPackagesRoute
  '/manager/therapy/$sessionId': typeof ManagerTherapySessionIdRoute
  '/manager/therapy/new': typeof ManagerTherapyNewRoute
  '/super-admin/branches/$branchId': typeof SuperAdminBranchesBranchIdRoute
  '/manager/assessments': typeof ManagerAssessmentsIndexRoute
  '/manager/expense': typeof ManagerExpenseIndexRoute
  '/manager/follow-up': typeof ManagerFollowUpIndexRoute
  '/manager/materials': typeof ManagerMaterialsIndexRoute
  '/manager/outdoor': typeof ManagerOutdoorIndexRoute
  '/manager/packages': typeof ManagerPackagesIndexRoute
  '/manager/patients': typeof ManagerPatientsIndexRoute
  '/manager/payments': typeof ManagerPaymentsIndexRoute
  '/manager/therapy': typeof ManagerTherapyIndexRoute
  '/super-admin/branches': typeof SuperAdminBranchesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/manager': typeof ManagerRouteWithChildren
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/manager/dashboard': typeof ManagerDashboardRoute
  '/manager/sales': typeof ManagerSalesRoute
  '/super-admin/dashboard': typeof SuperAdminDashboardRoute
  '/auth/': typeof AuthIndexRoute
  '/manager/': typeof ManagerIndexRoute
  '/super-admin/': typeof SuperAdminIndexRoute
  '/manager/assessments/$assessmentId': typeof ManagerAssessmentsAssessmentIdRoute
  '/manager/assessments/new': typeof ManagerAssessmentsNewRoute
  '/manager/follow-up/$followUpId': typeof ManagerFollowUpFollowUpIdRoute
  '/manager/materials/$materialId': typeof ManagerMaterialsMaterialIdRoute
  '/manager/materials/new': typeof ManagerMaterialsNewRoute
  '/manager/outdoor/$visitId': typeof ManagerOutdoorVisitIdRoute
  '/manager/outdoor/new': typeof ManagerOutdoorNewRoute
  '/manager/patients/$patientId': typeof ManagerPatientsPatientIdRoute
  '/manager/payments/$paymentId': typeof ManagerPaymentsPaymentIdRoute
  '/manager/payments/collect': typeof ManagerPaymentsCollectRoute
  '/manager/payments/packages': typeof ManagerPaymentsPackagesRoute
  '/manager/therapy/$sessionId': typeof ManagerTherapySessionIdRoute
  '/manager/therapy/new': typeof ManagerTherapyNewRoute
  '/super-admin/branches/$branchId': typeof SuperAdminBranchesBranchIdRoute
  '/manager/assessments/': typeof ManagerAssessmentsIndexRoute
  '/manager/expense/': typeof ManagerExpenseIndexRoute
  '/manager/follow-up/': typeof ManagerFollowUpIndexRoute
  '/manager/materials/': typeof ManagerMaterialsIndexRoute
  '/manager/outdoor/': typeof ManagerOutdoorIndexRoute
  '/manager/packages/': typeof ManagerPackagesIndexRoute
  '/manager/patients/': typeof ManagerPatientsIndexRoute
  '/manager/payments/': typeof ManagerPaymentsIndexRoute
  '/manager/therapy/': typeof ManagerTherapyIndexRoute
  '/super-admin/branches/': typeof SuperAdminBranchesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/manager'
    | '/super-admin'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/manager/dashboard'
    | '/manager/sales'
    | '/super-admin/dashboard'
    | '/auth/'
    | '/manager/'
    | '/super-admin/'
    | '/manager/assessments/$assessmentId'
    | '/manager/assessments/new'
    | '/manager/follow-up/$followUpId'
    | '/manager/materials/$materialId'
    | '/manager/materials/new'
    | '/manager/outdoor/$visitId'
    | '/manager/outdoor/new'
    | '/manager/patients/$patientId'
    | '/manager/payments/$paymentId'
    | '/manager/payments/collect'
    | '/manager/payments/packages'
    | '/manager/therapy/$sessionId'
    | '/manager/therapy/new'
    | '/super-admin/branches/$branchId'
    | '/manager/assessments/'
    | '/manager/expense/'
    | '/manager/follow-up/'
    | '/manager/materials/'
    | '/manager/outdoor/'
    | '/manager/packages/'
    | '/manager/patients/'
    | '/manager/payments/'
    | '/manager/therapy/'
    | '/super-admin/branches/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/manager/dashboard'
    | '/manager/sales'
    | '/super-admin/dashboard'
    | '/auth'
    | '/manager'
    | '/super-admin'
    | '/manager/assessments/$assessmentId'
    | '/manager/assessments/new'
    | '/manager/follow-up/$followUpId'
    | '/manager/materials/$materialId'
    | '/manager/materials/new'
    | '/manager/outdoor/$visitId'
    | '/manager/outdoor/new'
    | '/manager/patients/$patientId'
    | '/manager/payments/$paymentId'
    | '/manager/payments/collect'
    | '/manager/payments/packages'
    | '/manager/therapy/$sessionId'
    | '/manager/therapy/new'
    | '/super-admin/branches/$branchId'
    | '/manager/assessments'
    | '/manager/expense'
    | '/manager/follow-up'
    | '/manager/materials'
    | '/manager/outdoor'
    | '/manager/packages'
    | '/manager/patients'
    | '/manager/payments'
    | '/manager/therapy'
    | '/super-admin/branches'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/manager'
    | '/super-admin'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/manager/dashboard'
    | '/manager/sales'
    | '/super-admin/dashboard'
    | '/auth/'
    | '/manager/'
    | '/super-admin/'
    | '/manager/assessments/$assessmentId'
    | '/manager/assessments/new'
    | '/manager/follow-up/$followUpId'
    | '/manager/materials/$materialId'
    | '/manager/materials/new'
    | '/manager/outdoor/$visitId'
    | '/manager/outdoor/new'
    | '/manager/patients/$patientId'
    | '/manager/payments/$paymentId'
    | '/manager/payments/collect'
    | '/manager/payments/packages'
    | '/manager/therapy/$sessionId'
    | '/manager/therapy/new'
    | '/super-admin/branches/$branchId'
    | '/manager/assessments/'
    | '/manager/expense/'
    | '/manager/follow-up/'
    | '/manager/materials/'
    | '/manager/outdoor/'
    | '/manager/packages/'
    | '/manager/patients/'
    | '/manager/payments/'
    | '/manager/therapy/'
    | '/super-admin/branches/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  ManagerRoute: typeof ManagerRouteWithChildren
  SuperAdminRoute: typeof SuperAdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/manager/': {
      id: '/manager/'
      path: '/'
      fullPath: '/manager/'
      preLoaderRoute: typeof ManagerIndexRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/dashboard': {
      id: '/manager/dashboard'
      path: '/dashboard'
      fullPath: '/manager/dashboard'
      preLoaderRoute: typeof ManagerDashboardRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/sales': {
      id: '/manager/sales'
      path: '/sales'
      fullPath: '/manager/sales'
      preLoaderRoute: typeof ManagerSalesRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/super-admin/': {
      id: '/super-admin/'
      path: '/'
      fullPath: '/super-admin/'
      preLoaderRoute: typeof SuperAdminIndexRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/dashboard': {
      id: '/super-admin/dashboard'
      path: '/dashboard'
      fullPath: '/super-admin/dashboard'
      preLoaderRoute: typeof SuperAdminDashboardRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/manager/assessments/': {
      id: '/manager/assessments/'
      path: '/assessments'
      fullPath: '/manager/assessments/'
      preLoaderRoute: typeof ManagerAssessmentsIndexRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/assessments/$assessmentId': {
      id: '/manager/assessments/$assessmentId'
      path: '/assessments/$assessmentId'
      fullPath: '/manager/assessments/$assessmentId'
      preLoaderRoute: typeof ManagerAssessmentsAssessmentIdRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/assessments/new': {
      id: '/manager/assessments/new'
      path: '/assessments/new'
      fullPath: '/manager/assessments/new'
      preLoaderRoute: typeof ManagerAssessmentsNewRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/expense/': {
      id: '/manager/expense/'
      path: '/expense'
      fullPath: '/manager/expense/'
      preLoaderRoute: typeof ManagerExpenseIndexRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/follow-up/': {
      id: '/manager/follow-up/'
      path: '/follow-up'
      fullPath: '/manager/follow-up/'
      preLoaderRoute: typeof ManagerFollowUpIndexRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/follow-up/$followUpId': {
      id: '/manager/follow-up/$followUpId'
      path: '/follow-up/$followUpId'
      fullPath: '/manager/follow-up/$followUpId'
      preLoaderRoute: typeof ManagerFollowUpFollowUpIdRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/materials/': {
      id: '/manager/materials/'
      path: '/materials'
      fullPath: '/manager/materials/'
      preLoaderRoute: typeof ManagerMaterialsIndexRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/materials/$materialId': {
      id: '/manager/materials/$materialId'
      path: '/materials/$materialId'
      fullPath: '/manager/materials/$materialId'
      preLoaderRoute: typeof ManagerMaterialsMaterialIdRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/materials/new': {
      id: '/manager/materials/new'
      path: '/materials/new'
      fullPath: '/manager/materials/new'
      preLoaderRoute: typeof ManagerMaterialsNewRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/outdoor/': {
      id: '/manager/outdoor/'
      path: '/outdoor'
      fullPath: '/manager/outdoor/'
      preLoaderRoute: typeof ManagerOutdoorIndexRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/outdoor/$visitId': {
      id: '/manager/outdoor/$visitId'
      path: '/outdoor/$visitId'
      fullPath: '/manager/outdoor/$visitId'
      preLoaderRoute: typeof ManagerOutdoorVisitIdRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/outdoor/new': {
      id: '/manager/outdoor/new'
      path: '/outdoor/new'
      fullPath: '/manager/outdoor/new'
      preLoaderRoute: typeof ManagerOutdoorNewRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/packages/': {
      id: '/manager/packages/'
      path: '/packages'
      fullPath: '/manager/packages/'
      preLoaderRoute: typeof ManagerPackagesIndexRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/patients/': {
      id: '/manager/patients/'
      path: '/patients'
      fullPath: '/manager/patients/'
      preLoaderRoute: typeof ManagerPatientsIndexRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/patients/$patientId': {
      id: '/manager/patients/$patientId'
      path: '/patients/$patientId'
      fullPath: '/manager/patients/$patientId'
      preLoaderRoute: typeof ManagerPatientsPatientIdRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/payments/': {
      id: '/manager/payments/'
      path: '/payments'
      fullPath: '/manager/payments/'
      preLoaderRoute: typeof ManagerPaymentsIndexRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/payments/$paymentId': {
      id: '/manager/payments/$paymentId'
      path: '/payments/$paymentId'
      fullPath: '/manager/payments/$paymentId'
      preLoaderRoute: typeof ManagerPaymentsPaymentIdRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/payments/collect': {
      id: '/manager/payments/collect'
      path: '/payments/collect'
      fullPath: '/manager/payments/collect'
      preLoaderRoute: typeof ManagerPaymentsCollectRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/payments/packages': {
      id: '/manager/payments/packages'
      path: '/payments/packages'
      fullPath: '/manager/payments/packages'
      preLoaderRoute: typeof ManagerPaymentsPackagesRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/therapy/': {
      id: '/manager/therapy/'
      path: '/therapy'
      fullPath: '/manager/therapy/'
      preLoaderRoute: typeof ManagerTherapyIndexRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/therapy/$sessionId': {
      id: '/manager/therapy/$sessionId'
      path: '/therapy/$sessionId'
      fullPath: '/manager/therapy/$sessionId'
      preLoaderRoute: typeof ManagerTherapySessionIdRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/therapy/new': {
      id: '/manager/therapy/new'
      path: '/therapy/new'
      fullPath: '/manager/therapy/new'
      preLoaderRoute: typeof ManagerTherapyNewRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/super-admin/branches/': {
      id: '/super-admin/branches/'
      path: '/branches'
      fullPath: '/super-admin/branches/'
      preLoaderRoute: typeof SuperAdminBranchesIndexRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/branches/$branchId': {
      id: '/super-admin/branches/$branchId'
      path: '/branches/$branchId'
      fullPath: '/super-admin/branches/$branchId'
      preLoaderRoute: typeof SuperAdminBranchesBranchIdRouteImport
      parentRoute: typeof SuperAdminRoute
    }
  }
}

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ManagerRouteChildren {
  ManagerDashboardRoute: typeof ManagerDashboardRoute
  ManagerSalesRoute: typeof ManagerSalesRoute
  ManagerIndexRoute: typeof ManagerIndexRoute
  ManagerAssessmentsAssessmentIdRoute: typeof ManagerAssessmentsAssessmentIdRoute
  ManagerAssessmentsNewRoute: typeof ManagerAssessmentsNewRoute
  ManagerFollowUpFollowUpIdRoute: typeof ManagerFollowUpFollowUpIdRoute
  ManagerMaterialsMaterialIdRoute: typeof ManagerMaterialsMaterialIdRoute
  ManagerMaterialsNewRoute: typeof ManagerMaterialsNewRoute
  ManagerOutdoorVisitIdRoute: typeof ManagerOutdoorVisitIdRoute
  ManagerOutdoorNewRoute: typeof ManagerOutdoorNewRoute
  ManagerPatientsPatientIdRoute: typeof ManagerPatientsPatientIdRoute
  ManagerPaymentsPaymentIdRoute: typeof ManagerPaymentsPaymentIdRoute
  ManagerPaymentsCollectRoute: typeof ManagerPaymentsCollectRoute
  ManagerPaymentsPackagesRoute: typeof ManagerPaymentsPackagesRoute
  ManagerTherapySessionIdRoute: typeof ManagerTherapySessionIdRoute
  ManagerTherapyNewRoute: typeof ManagerTherapyNewRoute
  ManagerAssessmentsIndexRoute: typeof ManagerAssessmentsIndexRoute
  ManagerExpenseIndexRoute: typeof ManagerExpenseIndexRoute
  ManagerFollowUpIndexRoute: typeof ManagerFollowUpIndexRoute
  ManagerMaterialsIndexRoute: typeof ManagerMaterialsIndexRoute
  ManagerOutdoorIndexRoute: typeof ManagerOutdoorIndexRoute
  ManagerPackagesIndexRoute: typeof ManagerPackagesIndexRoute
  ManagerPatientsIndexRoute: typeof ManagerPatientsIndexRoute
  ManagerPaymentsIndexRoute: typeof ManagerPaymentsIndexRoute
  ManagerTherapyIndexRoute: typeof ManagerTherapyIndexRoute
}

const ManagerRouteChildren: ManagerRouteChildren = {
  ManagerDashboardRoute: ManagerDashboardRoute,
  ManagerSalesRoute: ManagerSalesRoute,
  ManagerIndexRoute: ManagerIndexRoute,
  ManagerAssessmentsAssessmentIdRoute: ManagerAssessmentsAssessmentIdRoute,
  ManagerAssessmentsNewRoute: ManagerAssessmentsNewRoute,
  ManagerFollowUpFollowUpIdRoute: ManagerFollowUpFollowUpIdRoute,
  ManagerMaterialsMaterialIdRoute: ManagerMaterialsMaterialIdRoute,
  ManagerMaterialsNewRoute: ManagerMaterialsNewRoute,
  ManagerOutdoorVisitIdRoute: ManagerOutdoorVisitIdRoute,
  ManagerOutdoorNewRoute: ManagerOutdoorNewRoute,
  ManagerPatientsPatientIdRoute: ManagerPatientsPatientIdRoute,
  ManagerPaymentsPaymentIdRoute: ManagerPaymentsPaymentIdRoute,
  ManagerPaymentsCollectRoute: ManagerPaymentsCollectRoute,
  ManagerPaymentsPackagesRoute: ManagerPaymentsPackagesRoute,
  ManagerTherapySessionIdRoute: ManagerTherapySessionIdRoute,
  ManagerTherapyNewRoute: ManagerTherapyNewRoute,
  ManagerAssessmentsIndexRoute: ManagerAssessmentsIndexRoute,
  ManagerExpenseIndexRoute: ManagerExpenseIndexRoute,
  ManagerFollowUpIndexRoute: ManagerFollowUpIndexRoute,
  ManagerMaterialsIndexRoute: ManagerMaterialsIndexRoute,
  ManagerOutdoorIndexRoute: ManagerOutdoorIndexRoute,
  ManagerPackagesIndexRoute: ManagerPackagesIndexRoute,
  ManagerPatientsIndexRoute: ManagerPatientsIndexRoute,
  ManagerPaymentsIndexRoute: ManagerPaymentsIndexRoute,
  ManagerTherapyIndexRoute: ManagerTherapyIndexRoute,
}

const ManagerRouteWithChildren =
  ManagerRoute._addFileChildren(ManagerRouteChildren)

interface SuperAdminRouteChildren {
  SuperAdminDashboardRoute: typeof SuperAdminDashboardRoute
  SuperAdminIndexRoute: typeof SuperAdminIndexRoute
  SuperAdminBranchesBranchIdRoute: typeof SuperAdminBranchesBranchIdRoute
  SuperAdminBranchesIndexRoute: typeof SuperAdminBranchesIndexRoute
}

const SuperAdminRouteChildren: SuperAdminRouteChildren = {
  SuperAdminDashboardRoute: SuperAdminDashboardRoute,
  SuperAdminIndexRoute: SuperAdminIndexRoute,
  SuperAdminBranchesBranchIdRoute: SuperAdminBranchesBranchIdRoute,
  SuperAdminBranchesIndexRoute: SuperAdminBranchesIndexRoute,
}

const SuperAdminRouteWithChildren = SuperAdminRoute._addFileChildren(
  SuperAdminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  ManagerRoute: ManagerRouteWithChildren,
  SuperAdminRoute: SuperAdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
